spring:
    application:
        name: spring-practice-webclient

    security:
        oauth2:
            client:
                provider:
                    springauth:
                        token-uri: http://localhost:9000/oauth2/token
                registration:
                    springauth:
                        client-name: springauth
                        client-id: messaging-client
                        client-secret: secret
                        scope:
                            - message.read
                            - message.write
                        authorization-grant-type: client_credentials
                        provider: springauth

server:
    port: 8083

webclient:
    baseUrl: http://localhost:8082
